---
apiVersion: "cilium.io/v2"
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: dns-visibility
spec:
  description: Globally allow DNS traffic to the K8s internal coredns. Otherwise this would not work anymore after you apply another egress CNP / CCNP in the user workload namespace / cluster.
  endpointSelector: {}
  egress:
  # # Allow all egress traffic to not break stuff. Remove for zero trust approach on the cluster!
  # - toEntities:
  #   - all
  # Allow DNS to coredns and matchPattern to activate DNS visibility
  - toEndpoints:
    - matchLabels:
        k8s:io.kubernetes.pod.namespace: kube-system
        k8s-app: kube-dns
    toPorts:
    - ports:
      - port: "53"
        protocol: ANY
      rules:
        dns:
        - matchPattern: "*"