---
apiVersion: "cilium.io/v2"
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: global-infra
spec:
  description: Globally allow interaction with infra components like Prometheus and coredns
  endpointSelector: {}
  ingress:
  # Allow Prometheus to scrape everything
  - fromEndpoints:
    - matchLabels:
        k8s:io.kubernetes.pod.namespace: monitoring
        k8s:app.kubernetes.io/name: prometheus
  # Cilium control plane health endpoint HTTP checks
  - fromEntities:
    - remote-node
    toPorts:
    - ports:
      - port: "4240"
        protocol: ANY
  # Cilium control plane health endpoint ICMP checks
  - fromEntities:
    - remote-node
    icmps:
    - fields:
      - type: 8
        family: IPv4
  # Allow coredns access from everywhere
  egress:
  - toEndpoints:
    - matchLabels:
        k8s:io.kubernetes.pod.namespace: kube-system
        k8s:k8s-app: kube-dns
    toPorts:
    - ports:
      - port: "53"
        protocol: ANY
      rules:
        dns:
        - matchPattern: "*"