apiVersion: "cilium.io/v2"
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: "host-all"
spec:
  description: "Cilium host policy for all nodes"
  nodeSelector:
    matchLabels:
      kubernetes.io/os: linux
  ingress:
  # Data plane inter-node connectivity
  - fromEntities:
    - host
    - remote-node
    toPorts:
    - ports:
        # Cilium VXLAN
      - port: "8472"
        protocol: UDP
        # Cilium WireGuard
      - port: "51871"
        protocol: UDP
  # Control plane health ICMP inter-node connectivity
  - fromEntities:
    - health
    - host
    - remote-node
    # Allow ICMP health checks
    icmps:
    - fields:
      - type: 8
        family: IPv4
  # Control plane health inter-node connectivity
  - fromEntities:
    - health
    - host
    - remote-node
    toPorts:
    - ports:
        # Inter-node Cilium cluster health checks (please also have a look at the appendix for further details)
      - port: "4240"
        protocol: TCP
        # Cilium cilium-agent health status API
      - port: "9876"
        protocol: TCP
  # Control plane connectivity from cluster
  - fromEntities:
    - cluster
    toPorts:
    - ports:
        # Prometheus Node Exporter
      - port: "9100"
        protocol: TCP
        # Cilium Agent Prometheus metrics
      - port: "9962"
        protocol: TCP
        # Cilium Operator Prometheus metrics
      - port: "9963"
        protocol: TCP
        # Cilium Envoy Prometheus metrics
      - port: "9964"
        protocol: TCP
        # Cilium Hubble Prometheus metrics
      - port: "9965"
        protocol: TCP
        # Kubelet metrics
      - port: "10250"
        protocol: TCP
        # Nginx ingress metrics
      - port: "10254"
        protocol: TCP
  # System access from external and nodes
  - fromEntities:
    - host
    - remote-node
    - world
    toPorts:
    - ports:
        # SSH
      - port: "22"
        protocol: TCP