affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: node-role.kubernetes.io/infra
          operator: Exists
tolerations:
- key: node-role.kubernetes.io/infra
  operator: Exists
  effect: NoSchedule
cainjector:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: node-role.kubernetes.io/infra
            operator: Exists
  tolerations:
  - key: node-role.kubernetes.io/infra
    operator: Exists
    effect: NoSchedule
webhook:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: node-role.kubernetes.io/infra
            operator: Exists
  tolerations:
  - key: node-role.kubernetes.io/infra
    operator: Exists
    effect: NoSchedule