name: Validation Actions
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  formatting:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: terraform fmt
        uses: dflook/terraform-fmt-check@v1
        with:
          path: deploy/
  docs:
    runs-on: ubuntu-22.04
    needs: formatting
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Render terraform docs inside the README.md and push changes back to PR branch
        uses: terraform-docs/gh-actions@d1c99433f7a1e5003ef213d70f89aaa47cb0b675
        with:
          working-dir: deploy/
          output-file: README.md
          output-method: inject
          output-format: markdown table
          indention: 3
          git-push: "true"
  validate-netpol-yamls:
    runs-on: ubuntu-22.04
    needs: formatting
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Validate Network Policy YAML files
        run: yamllint netpols/*/*.yaml
  validate-cilium-valuesyaml:
    runs-on: ubuntu-22.04
    needs: formatting
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Validate Cilium Helm values YAML file
        run: yamllint deploy/03-cilium-values-1.14.yaml
